# Generated by Django 5.2.1 on 2025-05-19 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
